 head_mcu_node:
        ros__parameters:
            serial_port: "/dev/ttyACM0"
            publish_rate: 10
            calibration_val: [    0, -1.,
                              65500,  1.,
                             ]