teleop_node:
  ros__parameters:
    axis_linear.x: 2
    scale_linear.x: .5
    scale_linear_turbo.x: 0.4
    
    # this is for steering angle velocity
    axis_linear.z: 2
    scale_linear.z: 0.6
    scale_linear_turbo.z: 0.7

    axis_angular.yaw: 3
    scale_angular.yaw: 1.4
    scale_angular_turbo.yaw: .8

    enable_button: 5  # R1 shoulder button
    enable_turbo_button: 4  # L1 shoulder button
