controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    pilsbot_joint_publisher:
      type: joint_state_broadcaster/JointStateBroadcaster

    pilsbot_velocity_controller:
      type: acker_diff_controller/AckerDiffController

pilsbot_velocity_controller:
  ros__parameters:
    left_wheel_names  : ['front_wheel_left_joint']
    right_wheel_names : ['front_wheel_right_joint']
    steering_axle_name : 'steering_axle_joint'
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  
    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    # FIXME: Somehow this does not work anymore... Config von gazebo rausgenommen, glaube ich
    wheel_separation : 0.62
    wheel_radius : 0.125
  
    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0
  
    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5
  
    # Base frame_id
    base_frame_id: base_link
    allow_multiple_cmd_vel_publishers: true
    odom_frame_id: 'odom_raw'
    enable_odom_tf: false
  
    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits    : true
    linear.x.max_velocity           : 1.5  # m/s
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration       : 0.5  # m/s^2
    linear.x.has_jerk_limits        : false
    linear.x.max_jerk               : 0.1  # m/s^3

    angle.z.has_position_limits      : true
    angle.z.max_angle                : 1.5	# rad, so ~89 Deg

    angular.z.has_velocity_limits    : true
    angular.z.max_velocity           : 1.0  # rad/s
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration       : 1.0  # rad/s^2
    angular.z.has_jerk_limits        : false
    angular.z.max_jerk               : 3.14  # rad/s^3
